import type { NextPage } from "next";
import { ReactElement } from "react";
import Head from "next/head";

import { Header } from "../components";

const Home: NextPage = (): ReactElement => {
  return (
    <>
      <Head>
        <title>world.trip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </>
  );
};

export default Home;
